
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BEGIN BGROUND BTNCANCEL BTNOK BUTTON CBOX CHBOX COMMA DPOINTS END FORM GRAY GREEN ID LBRACKET LIST NUMBER ONCLICK PANEL QUOTES RBRACKET RED SIZE STRING TBOX TEXT TITLE VALUES WHITEdocument : FORM ID formform : BEGIN formComponent ENDformComponent : panelFeatures componentpanelFeatures : panelTitle size backgroundpanelTitle : TITLE DPOINTS QUOTES STRING QUOTESsize : SIZE DPOINTS LBRACKET NUMBER COMMA NUMBER RBRACKETbackground : BGROUND DPOINTS colorcolor : WHITEcolor : REDcolor : GREENcolor : GRAYcomponent : panelcomponent : textBoxcomponent : comboBoxcomponent : checkBoxcomponent : buttoncomponent : emptypanel : PANEL ID BEGIN panelFeatures component END componenttextBox : TBOX ID BEGIN textBoxFeatures END componenttextBoxFeatures : text size backgroundtext : TEXT DPOINTS QUOTES STRING QUOTEScomboBox : CBOX ID BEGIN comboBoxFeatures END componentcomboBoxFeatures : list comboBoxValues size backgroundlist : LIST DPOINTS LBRACKET listValues RBRACKETlistValues : ID llValuesllValues : COMMA ID llValuesllValues : emptycomboBoxValues : VALUES DPOINTS LBRACKET valuesValues RBRACKETvaluesValues : NUMBER lvValueslvValues : COMMA NUMBER lvValueslvValues : emptycheckBox : CHBOX ID BEGIN list END componentbutton : BUTTON ID BEGIN buttonFeatures END componentbuttonFeatures : text background buttonOnClickbuttonOnClick : ONCLICK DPOINTS buttonActionbuttonAction : BTNOKbuttonAction : BTNCANCELempty :'
    
_lr_action_items = {'FORM':([0,],[2,]),'$end':([1,4,10,],[0,-1,-2,]),'ID':([2,18,19,20,21,22,79,98,],[3,26,27,28,29,30,90,107,]),'BEGIN':([3,26,27,28,29,30,],[5,35,36,37,38,39,]),'TITLE':([5,35,],[9,9,]),'END':([6,7,11,12,13,14,15,16,17,31,43,44,47,50,51,53,54,55,56,57,60,61,64,68,69,72,73,74,76,80,81,82,85,87,96,100,101,102,],[10,-38,-3,-12,-13,-14,-15,-16,-17,-4,-38,61,64,68,69,-7,-8,-9,-10,-11,72,-38,-38,-38,-38,-38,-19,-20,-22,-32,-33,-34,-18,-23,-24,-35,-36,-37,]),'PANEL':([7,31,43,53,54,55,56,57,61,64,68,69,72,],[18,-4,18,-7,-8,-9,-10,-11,18,18,18,18,18,]),'TBOX':([7,31,43,53,54,55,56,57,61,64,68,69,72,],[19,-4,19,-7,-8,-9,-10,-11,19,19,19,19,19,]),'CBOX':([7,31,43,53,54,55,56,57,61,64,68,69,72,],[20,-4,20,-7,-8,-9,-10,-11,20,20,20,20,20,]),'CHBOX':([7,31,43,53,54,55,56,57,61,64,68,69,72,],[21,-4,21,-7,-8,-9,-10,-11,21,21,21,21,21,]),'BUTTON':([7,31,43,53,54,55,56,57,61,64,68,69,72,],[22,-4,22,-7,-8,-9,-10,-11,22,22,22,22,22,]),'SIZE':([8,45,59,65,93,103,],[24,24,-5,24,-21,-28,]),'DPOINTS':([9,24,32,46,49,66,83,],[25,33,40,63,67,78,91,]),'BGROUND':([23,52,62,77,92,93,],[32,32,32,32,-6,-21,]),'QUOTES':([25,42,63,86,],[34,59,75,93,]),'LBRACKET':([33,67,78,],[41,79,88,]),'STRING':([34,75,],[42,86,]),'TEXT':([36,39,],[46,46,]),'LIST':([37,38,],[49,49,]),'WHITE':([40,],[54,]),'RED':([40,],[55,]),'GREEN':([40,],[56,]),'GRAY':([40,],[57,]),'NUMBER':([41,71,88,105,],[58,84,95,108,]),'VALUES':([48,96,],[66,-24,]),'ONCLICK':([53,54,55,56,57,70,],[-7,-8,-9,-10,-11,83,]),'COMMA':([58,90,95,107,108,],[71,98,105,98,105,]),'RBRACKET':([84,89,90,94,95,97,99,104,106,107,108,109,110,],[92,96,-38,103,-38,-25,-27,-29,-31,-38,-38,-26,-30,]),'BTNOK':([91,],[101,]),'BTNCANCEL':([91,],[102,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'document':([0,],[1,]),'form':([3,],[4,]),'formComponent':([5,],[6,]),'panelFeatures':([5,35,],[7,43,]),'panelTitle':([5,35,],[8,8,]),'component':([7,43,61,64,68,69,72,],[11,60,73,76,80,81,85,]),'panel':([7,43,61,64,68,69,72,],[12,12,12,12,12,12,12,]),'textBox':([7,43,61,64,68,69,72,],[13,13,13,13,13,13,13,]),'comboBox':([7,43,61,64,68,69,72,],[14,14,14,14,14,14,14,]),'checkBox':([7,43,61,64,68,69,72,],[15,15,15,15,15,15,15,]),'button':([7,43,61,64,68,69,72,],[16,16,16,16,16,16,16,]),'empty':([7,43,61,64,68,69,72,90,95,107,108,],[17,17,17,17,17,17,17,99,106,99,106,]),'size':([8,45,65,],[23,62,77,]),'background':([23,52,62,77,],[31,70,74,87,]),'textBoxFeatures':([36,],[44,]),'text':([36,39,],[45,52,]),'comboBoxFeatures':([37,],[47,]),'list':([37,38,],[48,50,]),'buttonFeatures':([39,],[51,]),'color':([40,],[53,]),'comboBoxValues':([48,],[65,]),'buttonOnClick':([70,],[82,]),'listValues':([79,],[89,]),'valuesValues':([88,],[94,]),'llValues':([90,107,],[97,109,]),'buttonAction':([91,],[100,]),'lvValues':([95,108,],[104,110,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> document","S'",1,None,None,None),
  ('document -> FORM ID form','document',3,'p_document','Parser.py',8),
  ('form -> BEGIN formComponent END','form',3,'p_form','Parser.py',13),
  ('formComponent -> panelFeatures component','formComponent',2,'p_formComponent','Parser.py',18),
  ('panelFeatures -> panelTitle size background','panelFeatures',3,'p_panelFeatures','Parser.py',23),
  ('panelTitle -> TITLE DPOINTS QUOTES STRING QUOTES','panelTitle',5,'p_panelTitle','Parser.py',28),
  ('size -> SIZE DPOINTS LBRACKET NUMBER COMMA NUMBER RBRACKET','size',7,'p_size','Parser.py',33),
  ('background -> BGROUND DPOINTS color','background',3,'p_background','Parser.py',38),
  ('color -> WHITE','color',1,'p_color1','Parser.py',43),
  ('color -> RED','color',1,'p_color2','Parser.py',48),
  ('color -> GREEN','color',1,'p_color3','Parser.py',53),
  ('color -> GRAY','color',1,'p_color4','Parser.py',58),
  ('component -> panel','component',1,'p_component1','Parser.py',63),
  ('component -> textBox','component',1,'p_component2','Parser.py',68),
  ('component -> comboBox','component',1,'p_component3','Parser.py',73),
  ('component -> checkBox','component',1,'p_component4','Parser.py',78),
  ('component -> button','component',1,'p_component5','Parser.py',83),
  ('component -> empty','component',1,'p_componentEmpty','Parser.py',88),
  ('panel -> PANEL ID BEGIN panelFeatures component END component','panel',7,'p_panel','Parser.py',93),
  ('textBox -> TBOX ID BEGIN textBoxFeatures END component','textBox',6,'p_textBox','Parser.py',98),
  ('textBoxFeatures -> text size background','textBoxFeatures',3,'p_textBoxFeatures','Parser.py',103),
  ('text -> TEXT DPOINTS QUOTES STRING QUOTES','text',5,'p_text','Parser.py',108),
  ('comboBox -> CBOX ID BEGIN comboBoxFeatures END component','comboBox',6,'p_comboBox','Parser.py',113),
  ('comboBoxFeatures -> list comboBoxValues size background','comboBoxFeatures',4,'p_comboBoxFeatures','Parser.py',118),
  ('list -> LIST DPOINTS LBRACKET listValues RBRACKET','list',5,'p_list','Parser.py',123),
  ('listValues -> ID llValues','listValues',2,'p_listValues','Parser.py',128),
  ('llValues -> COMMA ID llValues','llValues',3,'p_llValues','Parser.py',133),
  ('llValues -> empty','llValues',1,'p_llValuesEmpty','Parser.py',138),
  ('comboBoxValues -> VALUES DPOINTS LBRACKET valuesValues RBRACKET','comboBoxValues',5,'p_comboBoxValues','Parser.py',143),
  ('valuesValues -> NUMBER lvValues','valuesValues',2,'p_valuesValues','Parser.py',148),
  ('lvValues -> COMMA NUMBER lvValues','lvValues',3,'p_lvValues','Parser.py',153),
  ('lvValues -> empty','lvValues',1,'p_lvValuesEmpty','Parser.py',158),
  ('checkBox -> CHBOX ID BEGIN list END component','checkBox',6,'p_checkBox','Parser.py',163),
  ('button -> BUTTON ID BEGIN buttonFeatures END component','button',6,'p_button','Parser.py',168),
  ('buttonFeatures -> text background buttonOnClick','buttonFeatures',3,'p_buttonFeatures','Parser.py',173),
  ('buttonOnClick -> ONCLICK DPOINTS buttonAction','buttonOnClick',3,'p_buttonOnClick','Parser.py',178),
  ('buttonAction -> BTNOK','buttonAction',1,'p_buttonAction1','Parser.py',183),
  ('buttonAction -> BTNCANCEL','buttonAction',1,'p_buttonAction2','Parser.py',188),
  ('empty -> <empty>','empty',0,'p_empty','Parser.py',193),
]
