package FormPlusPlus.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_EnumColors extends EnumerationDescriptorBase {

  public EnumerationDescriptor_EnumColors() {
    super(0x33e7f45b147f42d0L, 0x86ff61e2bcaba42eL, 0x7e92237b5a39f786L, "EnumColors", "r:f92c8f3d-2aff-4472-82f4-c11cabfbb93c(FormPlusPlus.structure)/9120391208080373638");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_WHITE_0 = new EnumerationDescriptor.MemberDescriptor("WHITE", "WHITE", 0x7e92237b5a39f787L, "r:f92c8f3d-2aff-4472-82f4-c11cabfbb93c(FormPlusPlus.structure)/9120391208080373639");
  private final EnumerationDescriptor.MemberDescriptor myMember_RED_0 = new EnumerationDescriptor.MemberDescriptor("RED", "RED", 0x7e92237b5a39f788L, "r:f92c8f3d-2aff-4472-82f4-c11cabfbb93c(FormPlusPlus.structure)/9120391208080373640");
  private final EnumerationDescriptor.MemberDescriptor myMember_GREEN_0 = new EnumerationDescriptor.MemberDescriptor("GREEN", "GREEN", 0x7e92237b5a39f78bL, "r:f92c8f3d-2aff-4472-82f4-c11cabfbb93c(FormPlusPlus.structure)/9120391208080373643");
  private final EnumerationDescriptor.MemberDescriptor myMember_GRAY_0 = new EnumerationDescriptor.MemberDescriptor("GRAY", "GRAY", 0x7e92237b5a39f78fL, "r:f92c8f3d-2aff-4472-82f4-c11cabfbb93c(FormPlusPlus.structure)/9120391208080373647");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x33e7f45b147f42d0L, 0x86ff61e2bcaba42eL, 0x7e92237b5a39f786L, 0x7e92237b5a39f787L, 0x7e92237b5a39f788L, 0x7e92237b5a39f78bL, 0x7e92237b5a39f78fL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_WHITE_0, myMember_RED_0, myMember_GREEN_0, myMember_GRAY_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_WHITE_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "WHITE":
        return myMember_WHITE_0;
      case "RED":
        return myMember_RED_0;
      case "GREEN":
        return myMember_GREEN_0;
      case "GRAY":
        return myMember_GRAY_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
