package FormPlusPlus.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Background = 0;
  public static final int Button = 1;
  public static final int ButtonAction = 2;
  public static final int ButtonFeatures = 3;
  public static final int ButtonOnClick = 4;
  public static final int CheckBox = 5;
  public static final int Color = 6;
  public static final int ComboBox = 7;
  public static final int ComboBoxFeatures = 8;
  public static final int ComboBoxValues = 9;
  public static final int Component = 10;
  public static final int Document = 11;
  public static final int Form = 12;
  public static final int FormComponent = 13;
  public static final int List = 14;
  public static final int ListValues = 15;
  public static final int LlValues = 16;
  public static final int Panel = 17;
  public static final int PanelFeatures = 18;
  public static final int PanelTitle = 19;
  public static final int Size = 20;
  public static final int Text = 21;
  public static final int TextBox = 22;
  public static final int TextBoxFeatures = 23;
  public static final int ValuesValues = 24;
  public static final int Valuesvalue = 25;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x33e7f45b147f42d0L, 0x86ff61e2bcaba42eL);
    builder.put(0x7e92237b5a39f770L, Background);
    builder.put(0x7e92237b5a39f780L, Button);
    builder.put(0x7e92237b5a39f783L, ButtonAction);
    builder.put(0x7e92237b5a39f781L, ButtonFeatures);
    builder.put(0x7e92237b5a39f782L, ButtonOnClick);
    builder.put(0x7e92237b5a39f77fL, CheckBox);
    builder.put(0x7e92237b5a39f771L, Color);
    builder.put(0x7e92237b5a39f779L, ComboBox);
    builder.put(0x7e92237b5a39f77aL, ComboBoxFeatures);
    builder.put(0x7e92237b5a39f77cL, ComboBoxValues);
    builder.put(0x7e92237b5a39f772L, Component);
    builder.put(0x7e92237b5a39f76aL, Document);
    builder.put(0x7e92237b5a39f76bL, Form);
    builder.put(0x7e92237b5a39f76cL, FormComponent);
    builder.put(0x7e92237b5a39f77bL, List);
    builder.put(0x569314e2fbb68fafL, ListValues);
    builder.put(0x569314e2fbb68fceL, LlValues);
    builder.put(0x7e92237b5a39f775L, Panel);
    builder.put(0x7e92237b5a39f76dL, PanelFeatures);
    builder.put(0x7e92237b5a39f76eL, PanelTitle);
    builder.put(0x7e92237b5a39f76fL, Size);
    builder.put(0x7e92237b5a39f778L, Text);
    builder.put(0x7e92237b5a39f776L, TextBox);
    builder.put(0x7e92237b5a39f777L, TextBoxFeatures);
    builder.put(0x7e92237b5a39f77eL, ValuesValues);
    builder.put(0x7e92237b5a449817L, Valuesvalue);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
